import React, { useEffect } from 'react';
import { useSelector, useDispatch } from 'react-redux';
import { fetchReports } from '../features/reports/reportsSlice';

function ReportsPage() {
  const dispatch = useDispatch();
  const { items: reports, loading, error } = useSelector((state) => state.reports);

  useEffect(() => {
    dispatch(fetchReports());
  }, [dispatch]);

  if (loading) return <div className="loading">Loading reports...</div>;
  if (error) return <div className="error">Error: {error}</div>;

  return (
    <div>
      <h1>Reports</h1>
      <div className="card">
        <table className="table">
          <thead>
            <tr>
              <th>Report #</th>
              <th>Name</th>
              <th>Type</th>
              <th>Status</th>
              <th>Generated By</th>
              <th>Generated Date</th>
              <th>Period</th>
            </tr>
          </thead>
          <tbody>
            {reports.map((report) => (
              <tr key={report.id}>
                <td>{report.reportNumber}</td>
                <td>{report.name}</td>
                <td>{report.type}</td>
                <td>{report.status}</td>
                <td>{report.generatedBy}</td>
                <td>{new Date(report.generatedDate).toLocaleDateString()}</td>
                <td>
                  {new Date(report.startDate).toLocaleDateString()} - {new Date(report.endDate).toLocaleDateString()}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

export default ReportsPage;
